version: '2.1'
services:
#  nginx:
#    image: nginx:alpine
#    container_name: nginx
#    restart: always
#
#    networks:
#      - ih
#    ports:
#      - 8081:8081
#    depends_on:
#      - My_web
#
#    volumes:
#      - ./portal.conf:/etc/nginx/conf.d/default.conf
#  My_static:
#    image: "tianyifu/myproject:dev"
#    container_name: My_static
#    restart: always
#    networks:
#      - ih
  My_web:
    image: "tianyifu/myproject:dev"
    container_name: My_web
    restart: on-failure:10

    depends_on:
      - My_db
    ports:
      - 8081:8081
    networks:
      - ih

  My_db:
    image: mysql:latest
    container_name: My_db
    restart: on-failure:2
    networks:
      - ih
    environment:
      - MYSQL_ROOT_PASSWORD=comsc
      - MYSQL_DATABASE=talkative
    volumes:
      - ./src/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

networks:
  ih:
    name: ih
    driver: bridge
