# 使用openjdk:17-jdk-slim作为基础镜像
FROM openjdk:17-jdk-slim

# 更新apt源并安装python3和pip
RUN apt-get update && apt-get install -y python3 python3-pip

# 设置一个新的临时目录
ENV TMPDIR=/app/tmp

# 创建新的临时目录
RUN mkdir -p $TMPDIR

# 安装需要的Python库
RUN pip3 install pymysql gensim nltk transformers flair


